Linear Regression Exercise (Closed Form Solution)

In statistics, linear regression is a linear approach to modelling the relationship between a scalar response and one or more explanatory variables (also known as dependent and independent variables) [Wikipedia]. The closed form solution to finding the parameter $\theta$ of a linear regression model is given by $$\theta = (X^TX)^{-1}X^TY$$ where X are your features and Y is your target.

PART A

You will be implementing this model on a dataset of your choice using <b>numpy</b>.

Steps

1. Get any interesting dataset online. You can use this dataset repo [mcu dataset](https://archive.ics.uci.edu/ml/datasets.php). We will try to predict one of the features with continuous values. Set the continuous variable as your target column and other columns as your features i.e divide your dataset into $X$ and $y$.
Hint: download the dataset and use pandas to load the data into your environment. You should be familiar with this already.
2. We will bypass the step of exploring your data and assume that your data $(X, y)$ is linearly separable.
3. Create a class called LinearReg: 
    - the \_\_init\_\_ constructor will take hyperparameters for the model class. **Ignore this for this exercise as you do not currently have any hyperparameters**
    - the class will have two major methods **"fit"** and **"predict"**.
    - the fit method takes as input $X$ and $y$, and calculates $\theta$ using the formula above. Make sure you save $\theta$ in as a **class variable** after calculation.
    -  the predict function takes in $X$ and returns predictions as $\hat{y}$. Use the same data $X$ for prediction. Do not worry of overfitting the model at this point.
        $$\hat{Y}=X\theta$$
4. Next create a static method in your class, called **"rmse"** that takes in the original target **y** and your predictions **\hat{y}**, and uses them to calculate the mean square error in prediction (MSE). MSE is computed as;
$$MSE = \frac{\sum(y - \hat{y})^2}{N} $$
The MSE helps us to know how well we were able to model the data. Lower MSE is always better.
5. Run your linear regression model

To run your model
1. Instantiate the model class, model = LinearReg()
2. Run model.fit() with $(X, y)$ as arguments
3. Run $\hat{y}$ = model.predict() with $X$ as argument
4. Compare the predictions to the target with model.rmse(y, $\hat{y})$ . What is the rmse value?

PART B

Well, we have some bugs in our code and this next section will help to fix that. Linear regression models usually have a zeroth parameter, $\theta_0$ which helps to model the "bias" and gives an extra degree of freedom to the model. To fix this, we do the following.

5. Create a function, called **"add_ones"** which takes in $X$ and returns an augmented version where 1s have been concatenated with X. This implies that a new column is added to $X$ which contain ones. Call this new augmented data, $X_{new}$. The function should return $X_{new}$. Note that $X_{new}$ has one column more than $X$.
6. Edit your fit method **to add ones** to $X$ to make $X_{new}$ before computing $\theta$ in your code.
7. Now, calculate the $MSE$ for your predictions using this $X_{new}$. 

- Is it better than the previous MSE you got? Give any reason why it is better or not better.

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/gdrive') 

Mounted at /content/gdrive


In [ ]:
!ls '/content/gdrive/MyDrive'

 911.csv		   G2_AMMI2021_Bootcamp_project.zip
'Colab Notebooks'	   Intro_ML_Files.zip
 company_sales_data.csv    Lab-Exercises_2.pdf
'Exercises- Part2.ipynb'   machine.data


In [ ]:
path = '/content/gdrive/MyDrive/machine.data'

In [ ]:
data = pd.read_csv(path)

In [ ]:
data.head()

adviser    32/60  125   256   6000  256.1  16  128  198  199
0  amdahl   470v/7   29  8000  32000     32   8   32  269  253
1  amdahl  470v/7a   29  8000  32000     32   8   32  220  253
2  amdahl  470v/7b   29  8000  32000     32   8   32  172  253
3  amdahl  470v/7c   29  8000  16000     32   8   16  132  132
4  amdahl   470v/b   26  8000  32000     64   8   32  318  290

In [ ]:
data.tail()

adviser          32/60  125   256  6000  256.1  16  128  198  199
203  sperry           80/8  124  1000  8000      0   1    8   42   37
204  sperry  90/80-model-3   98  1000  8000     32   2    8   46   50
205  sratus             32  125  2000  8000      0   2   14   52   41
206    wang         vs-100  480   512  8000     32   0    0   67   47
207    wang          vs-90  480  1000  4000      0   0    0   45   25

In [ ]:
data.columns = ['Vendor','Model','MYCT','MMIN','MMAX','CACH','CHMIN','CHMAX','PRP','EER']

In [ ]:
data.head()

Vendor    Model  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  EER
0  amdahl   470v/7    29  8000  32000    32      8     32  269  253
1  amdahl  470v/7a    29  8000  32000    32      8     32  220  253
2  amdahl  470v/7b    29  8000  32000    32      8     32  172  253
3  amdahl  470v/7c    29  8000  16000    32      8     16  132  132
4  amdahl   470v/b    26  8000  32000    64      8     32  318  290

In [ ]:
data.isnull().sum()

Vendor    0
Model     0
MYCT      0
MMIN      0
MMAX      0
CACH      0
CHMIN     0
CHMAX     0
PRP       0
EER       0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Vendor  208 non-null    object
 1   Model   208 non-null    object
 2   MYCT    208 non-null    int64 
 3   MMIN    208 non-null    int64 
 4   MMAX    208 non-null    int64 
 5   CACH    208 non-null    int64 
 6   CHMIN   208 non-null    int64 
 7   CHMAX   208 non-null    int64 
 8   PRP     208 non-null    int64 
 9   EER     208 non-null    int64 
dtypes: int64(8), object(2)
memory usage: 16.4+ KB


In [ ]:
data.shape

(208, 10)

In [ ]:
X = data[data.columns[2:-1]]
X.head()

MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP
0    29  8000  32000    32      8     32  269
1    29  8000  32000    32      8     32  220
2    29  8000  32000    32      8     32  172
3    29  8000  16000    32      8     16  132
4    26  8000  32000    64      8     32  318

In [ ]:
y = data['EER']
y.head()

0    253
1    253
2    253
3    132
4    290
Name: EER, dtype: int64

In [ ]:
class LinearReg:
  def __init__(self):
    pass
  
  def fit(self, X, y):
    # theta = (X^T X)^(-1) X^T y
    self.theta = np.linalg.inv(X.T @ X) @ (X.T @ y)
    return self.theta

  def predict(self, X):
    return X @ self.theta

  def rmse(self, y, y_hat):
    N = len(X)
    MSE = (1/N) * sum((y - y_hat)**2)
    return MSE

In [ ]:
model = LinearReg()

In [ ]:
model.fit(X,y)

array([-0.0085281 ,  0.00348704,  0.00207142, -0.04210652, -0.11618218,
        0.05061422,  0.70313961])

In [ ]:
Y_hat = model.predict(X)
Y_hat.head()

0    282.421963
1    247.968122
2    214.217420
3    152.139213
4    315.553980
dtype: float64

In [ ]:
model.rmse(y, Y_hat)

1214.666391079379

PART  B

Well, we have some bugs in our code and this next section will help to fix that. Linear regression models usually have a zeroth parameter, $\theta_0$ which helps to model the "bias" and gives an extra degree of freedom to the model. To fix this, we do the following.

5. Create a function, called **"add_ones"** which takes in $X$ and returns an augmented version where 1s have been concatenated with X. This implies that a new column is added to $X$ which contain ones. Call this new augmented data, $X_{new}$. The function should return $X_{new}$. Note that $X_{new}$ has one column more than $X$.
6. Edit your fit method **to add ones** to $X$ to make $X_{new}$ before computing $\theta$ in your code.
7. Now, calculate the $MSE$ for your predictions using this $X_{new}$. 

- Is it better than the previous MSE you got? Give any reason why it is better or not better.

In [ ]:
class LinearReg:
  def __init__(self):
    pass

  def add_ones(self,X):
    ones_vector = np.ones(len(X))
    X_new =np.column_stack((X,ones_vector))
    return X_new

  def fit(self, X, y):
    X_new = self.add_ones(X)
    self.theta = np.linalg.inv(X_new.T @ X_new) @ (X_new.T @ y)
    return self.theta

  def predict(self, X):
    X_new = self.add_ones(X)
    return X_new @ self.theta

  def rmse(self, y, y_hat):
    N = len(X)
    MSE = (1/N) * sum((y - y_hat)**2)
    return MSE

In [ ]:
model = LinearReg()

In [ ]:
model.fit(X,y)

array([ 3.72784201e-02,  5.44988811e-03,  3.39974506e-03,  9.64847224e-02,
        1.89411638e-02,  3.17975359e-01,  5.81908031e-01, -3.39163655e+01])

In [ ]:
Y_hat = model.predict(X)
Y_hat

array([ 2.89503168e+02,  2.60989674e+02,  2.33058089e+02,  1.50298241e+02,
        3.20992337e+02,  3.93144629e+02,  4.64137409e+02,  6.58469731e+02,
        1.05793051e+03,  1.94115229e+01,  2.12735064e+01,  6.87878662e+01,
        1.33280588e+02, -1.31926190e+01,  6.13433394e+01, -1.36211246e+00,
        1.78047411e+01,  6.88528731e+00,  1.18464173e+02,  2.87348328e+01,
        3.50446991e+01,  6.09880704e+01,  7.28464135e+01,  1.63273151e+01,
        2.91130220e+01,  2.09361290e+01,  6.67745841e+00,  4.46034721e+01,
        1.44308746e+01,  1.63003282e+02,  2.17702637e+02,  4.72298918e+01,
        6.52690407e+01,  1.40456789e+02,  2.00109636e+02, -8.82712934e+00,
        6.25245246e+00,  4.97414581e+01,  4.54461070e+00,  2.39626712e+01,
        5.89381519e+01,  6.62390237e+01,  7.08942879e+01,  6.39267617e+01,
        5.03277814e+01,  1.23933058e+01,  3.07028453e+01,  3.32721102e+01,
        4.29405414e+01,  3.57719553e+01,  1.46758993e+01,  1.13968353e+02,
        2.77907481e+01,  

In [ ]:
model.rmse(y, Y_hat)

969.004014844691

Conclusion

So, MSE is a risk function that helps us determine the average squared difference between the predicted and the actual value of a feature or variable. For the first case, we did not consider thet intercept term and we got a value and when we consider the intercept term we got a value by comparing those two values, by considering the intercept term we got small value, i.e the error too small.
So it 's better to consider intercept term when you are predicting.

In [ ]:
"""
class LinearRegressionSGD:
  def __init__(self,num_iters,learn_rate):
    self.num_iters = num_iters
    self.learn_rate =  learn_rate
    self.theta = None
    

  def fit(self,X,Y,eps):
    (n, d) = X.shape
    self.theta = np.random.rand(X.shape[1])
    self.cost = []
    Y = Y.reshape(-1,1)
    for i in range(0,self.num_iters):
      #for j in range(len(X)):
      index = np.random.randint(n)
      xi = X[index].reshape(-1,d)
      yi = Y[index].reshape(-1,1)
      theta_prev = self.theta
      l = self.mse(yi,xi@theta_prev)
      #grad=np.dot(X_train[i].reshape(-1,1).T,(X_train[i].dot(theta ).reshape(-1,1)-Y_train[i].reshape(-1,1)))
      grad = xi.T@(xi @ self.theta - yi)
      self.theta = self.theta - (2/n)*self.learn_rate *grad
      self.cost.append(l) 
      if np.linalg.norm(theta_prev-self.theta)<=eps:
        break
      print('last i: ', i)
    return self.cost,self.theta
    

  def predict(self, X_test):
    y_predict = X_test @ self.theta
    return y_predict

  def mse(self,y, y_hat):
    N = len(Y_test)
    MSE = (1/N) * sum((y - y_hat)**2)
    return MSE """

"\nclass LinearRegressionSGD:\n  def __init__(self,num_iters,learn_rate):\n    self.num_iters = num_iters\n    self.learn_rate =  learn_rate\n    self.theta = None\n    \n\n  def fit(self,X,Y,eps):\n    (n, d) = X.shape\n    self.theta = np.random.rand(X.shape[1])\n    self.cost = []\n    Y = Y.reshape(-1,1)\n    for i in range(0,self.num_iters):\n      #for j in range(len(X)):\n      index = np.random.randint(n)\n      xi = X[index].reshape(-1,d)\n      yi = Y[index].reshape(-1,1)\n      theta_prev = self.theta\n      l = self.mse(yi,xi@theta_prev)\n      #grad=np.dot(X_train[i].reshape(-1,1).T,(X_train[i].dot(theta ).reshape(-1,1)-Y_train[i].reshape(-1,1)))\n      grad = xi.T@(xi @ self.theta - yi)\n      self.theta = self.theta - (2/n)*self.learn_rate *grad\n      self.cost.append(l) \n      if np.linalg.norm(theta_prev-self.theta)<=eps:\n        break\n      print('last i: ', i)\n    return self.cost,self.theta\n    \n\n  def predict(self, X_test):\n    y_predict = X_test @ self.th