<a href='https://aims-senegal.org/'> <img src='http://sn.nexteinstein.org/wp-content/uploads/sites/12/2016/07/aims_senegal.jpg' /></a>

In [ ]:
# run this cell first
import numpy as np



---



---



---



# Exercise A:




### 1- Construct a Ndarray  of shape (3, 2) filled with **8**, Then set element (0, 1) to 10, and element (1, 0) to 100

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

A = np.full((3,2), 8)
A
A[0,1]= 10
A[1,0] =100
A
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[  8,  10],
       [100,   8],
       [  8,   8]])

### 2- Create a 64-bit floating-point Ndarray of shape (6,) (six-element vector) filled with evenly-spaced values between 10 and 20. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


B = np.linspace(10,20,6)
B
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10., 12., 14., 16., 18., 20.])

In [ ]:
B.dtype

dtype('float64')

### 3- Create a vector with values ranging from 10 to 49

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
C = np.arange(10,49)
C
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### 4- Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

D = np.arange(0,9).reshape(3,3)
D

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5- Create a 10x10 array with random values and print the trace value and the mean values of each row

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


E =  np.random.random((10,10))

F = E.trace()
G = E.mean(axis=1)
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [ ]:
F

4.059220406516914

In [ ]:
np.trace(E)

4.059220406516914

In [ ]:
G

array([0.32652079, 0.40612317, 0.43180734, 0.46474155, 0.47944842,
       0.46603751, 0.50026341, 0.44363301, 0.44582565, 0.56643754])

### 6- Create a Ndarray array of size (5, 5) with all **1** on the borders and all **0** in the inside


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

H = np.ones((5,5))
H
H[1:-1,1:-1]=0
H
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 7- Create random vector of size 10 and replace the maximum value by 0

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


P = np.random.random(10)
P
P[P.argmax()] = 0
P
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([0.0537865 , 0.11191734, 0.83445863, 0.23941859, 0.04179706,
       0.32486866, 0.32034795, 0.78490505, 0.77253685, 0.        ])

### 8- Normalize a 5x5 random matrix
Hint: subtract the mean and devide by the standard deviation

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

K = np.random.random((5,5))
stdev = np.std(K)
Kmean = np.mean(K)
Y = (K- Kmean)/ stdev
Y

################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[ 1.36843454,  1.08734152, -2.01513622, -1.31323932, -0.05579597],
       [ 0.57832738,  0.62971756, -0.08864394, -1.34937019,  1.38877605],
       [ 0.4339861 , -0.43222743,  0.0975939 ,  1.14785523, -0.81632705],
       [-0.66948988, -0.22655974, -0.29831508, -1.11520335,  0.97033367],
       [-1.21907392,  0.99405199,  0.76918469,  1.38046098, -1.2466815 ]])

### 9- Create a random 5x2 matrix representing cartesian coordinates and print an array **"polar"** with same shape representing the converted polar coordinates.

Hints:

X represent the first column.

Y represent the second column.

Compute:

$$ R = \sqrt{X^2 + Y^2} $$

$$ T = \arctan{(Y, X)} $$


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
W = np.random.random((5,2))
x = W[:,0]
y = W[:,1]
R = np.sqrt(x**2+y**2)
T = np.arctan(y,x)
R
T

################################################################################
#       END OF YOUR CODE                                #
################################################################################

array([0.67739185, 0.61453729, 0.27652271, 0.01974563, 0.12150439])



---



---



---



### 10- Write a function that normalizes the columns of a matrix. It should compute the mean and standard deviation of each column, then subtract the mean and divide by the standard deviation for each element in the column. 

Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- The first column has mean 0 and std 1
- The second column has mean 20 and std 10
- The third column has mean 400 and std 200

After normalizing the columns, the result should be:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

Your implementation should not use any loops; instead you should use reduction and broadcasting operations.

In [ ]:


################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def normalize_columns(x):
  mean = np.mean(x,axis=0)
  stdev = np.std(x,axix=0)
  y = (x-mean)/stdev
  return y

  # x: (input) Ndarray of shape (N, M) (don't modefy it: use copy())
  # y: (return) Ndarray of shape (N, M) normalized by the columns
  
################################################################################
#                              END OF YOUR CODE   
                           #
################################################################################

In [ ]:
x0 = np.array([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1.224744871391589, 1.224744871391589], [1.224744871391589, -1.224744871391589, -1.224744871391589], [-1.224744871391589, 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]



---



---



---



### 11- creates a function that returns a matrix of **one-hot vectors** from a list of Python integers. A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are commonly used to represent categorical variables in machine learning models.

### For example, given a list `[1, 4, 3, 2]` of integers, your function should produce the tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

### Here the first row corresponds to the first element of the list: it has a one at index 1, and zeros at all other indices. The second row corresponds to the second element of the list: it has a one at index 4, and zeros at all other indices. The other rows follow the same pattern. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def make_one_hot(x):

  #x: (input) A list of n ints
  n = np.array(x)
  u = np.zeros((n.size, n.max()+1))
  u[np.arange(n.size),n]=1
  return u
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

Run the following cell to check your implementation, you must see 'all checks pass!' message

In [ ]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

Here is y0:
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]

Here is y1:
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
all checks pass!




---



---



---



# Exercise B:

### Maximum Likelihood
Find the maximum likelihood estimation of parameters $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N
$$

Steps to follow:


1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Compute the maximum likelihood estimation of parameters $\boldsymbol\theta$ following the equation and assign it to a variable called **theta**

$$
\boldsymbol\theta = (\boldsymbol X^T\boldsymbol X)^{-1}\boldsymbol X^T\boldsymbol y\in\mathbb{R}^D
$$

4. print the value of **theta**

Hint: check the inverse method from the linear algebra module in Numpy

In [ ]:
################################################################################
# TODO: Compute the maximum likelihood estimation of parameters theta
#       following the equation
################################################################################
from numpy.linalg import inv
N=10
X = np.random.random((10,5))
Y = np.ones((N,1))
theta = np.dot(inv(np.dot(X.T,X)),np.dot(X.T,Y))
theta

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[ 0.57541612],
       [-0.55762828],
       [ 0.36142586],
       [ 0.62709042],
       [ 0.85622081]])

In [ ]:

x

array([[0.96874844, 0.11076613, 0.16122408, 0.31285444, 0.38069111],
       [0.4534263 , 0.252535  , 0.6374832 , 0.09306801, 0.42514097],
       [0.35975576, 0.47663537, 0.1523523 , 0.70402439, 0.54109907],
       [0.39377219, 0.65306997, 0.59596346, 0.3519941 , 0.54438929],
       [0.24178334, 0.36575216, 0.47075136, 0.72749881, 0.13968423],
       [0.61565615, 0.34367241, 0.64170958, 0.55550068, 0.64462164],
       [0.21740975, 0.10724852, 0.09947936, 0.64492934, 0.42280824],
       [0.22695726, 0.36003922, 0.17564207, 0.41972702, 0.01146878],
       [0.77448641, 0.42748416, 0.62269027, 0.34777119, 0.25502209],
       [0.2384591 , 0.67843965, 0.91725713, 0.81905021, 0.14363706]])



---



---



---



# Exercise B:

### The Log Likelihood

Find the log likelihood estimation for input X, label y, parameterized by $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N \quad \boldsymbol \theta  \in\mathbb{R}^D
$$

steps to follow:

1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Initialize Ndarray **theta** randomly with shape D = 5 and reshape it to have the shape (D, 1).
4.   Compute the the probability of a all data points $(\boldsymbol x, y)$ being of class 1, given by

$$p(y = 1 | \boldsymbol X, \boldsymbol\theta) = 1.0/(1.0+\exp(- \boldsymbol X \boldsymbol \theta))$$

5. compute the log Likelihood, given by:
$$\log p(\boldsymbol y|\boldsymbol X, \boldsymbol\theta) = \sum_i y_i * \log (p(y = 1 | \boldsymbol x, \boldsymbol\theta) + (1 - y_i) * \log ( 1 - p(y = 1 | \boldsymbol x, \boldsymbol\theta))$$

6. print the log Likelihood

In [ ]:
################################################################################
# TODO: Compute the log likelihood 
#    
################################################################################


X = np.random.randn(10, 5)
y = np.ones((10,1))
theta = np.random.random((5, 1))

p = 1.0/(1 + np.exp(-X @ theta))
L = np.sum(y*np.log(p) + (1 - y)*np.log(1 - p))

print(L)
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

-6.856698565773221
